rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
  - jruby
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-2

before_install:
  - gem update --system
  - gem update bundler

bundler_args: --without guard docs

script: bundle exec rspec spec/ -b
